### ISSUE TITLE
2D poisson issue

### ISSUE THREAD

**Issue by moumenabdelhafidh** [OpenPIV/bos#1]
Hi,
As a new user in th BOS's world i'm tryind to deal with openpix/bos routines but i'm facing some issues in the poisson solver and rhs construction 

1. `du(k,j)=(u(k+1,j)-u(k-1,j))/2*(abs(x(2,2)-x(2,1)));`

why x(2,1) unstead the usualy used x(1,2) known that the first return a bignumber such as 800 and the second returns an acceptable number such as 8 or 16
Also using gradrient (u by x, v by y) i'm getting a very different result
2- in rhs we have:
`rhs=const*fliprl(rhs)`
 why fliping right here?
3- what's the physical and the mathematical meaning of 
```
PG2_gray=p*255;
n_max=1.43;    
n_min=1.332;
n2= scaledata(PG2_gray,n_min,n_max)
```

thanks in advance

**Comment by lillyverso** [comment]
Hello,

1. Please have a look to the structure of the velocity fields u and v (outputs of the piv correlation).
When the correlation function "BOS_correlation_OpenPIV"" runs on the images, it returns a matrix of 212X285 . The u and v fields are rotated of 90 degree. Therefore when you use x(1,2) instead of x(2,1) in the formula,  you are taking du/dy instead of du/dx.
Btw, just for fun,  I have modified the code by implementing  du(k,j)=(u(k+1,j)-u(k-1,j))/2*(abs(x(2,2)-x(1,2)))  and I did not get any big numbers. the displacements are reasonable from 8-16 as well (except some peripheral region of the images where piv-correlation error is high). 

2. rhs does not need fliplr. It is a left over. Feel free to remove it from your code. 
Anyhow the results of the original calculation is correct since flipping the rhs corresponds to flip the solution of the density around the y-axis.

3. also this point does need to be rescaled by 255. you can comment  PG2_gray=p*255; and substitute n2= scaledata(p,n_min,n_max). This hold in place the results from the Poisson integration. It limits the solution between n_min and n_max

Best

**Comment by moumenabdelhafidh** [comment]
Thank you so much i'll have a look right now, one more question please if you don't mind
in BOS theory i m confused : there are two different formulas that relate displacement dx to epsilon (angular defelection) wich guive different coefficients to the source term in poisson equation
1= dx= f(Zd/(Zd+Zc-f) * epsilon
2= dx= 0.5*W(W+2Zd)*epsilon 
Zd is backround-object distance and w is object's widh

**Comment by chandlersgk123** [comment]
hello,lilyverso, you said"also this point does need to be rescaled by 255. you can comment PG2_gray=p*255; and substitute n2= scaledata(p,n_min,n_max). This hold in place the results from the Poisson integration. It limits the solution between n_min and n_max",my question is why it should limit the solutio between n_min and n_max? in my case, how to determine the value of n_min and n_max? thank you !

**Comment by lillyverso** [comment]
Hello,

the Poisson integration need two boundaries conditions to be solved. You
might impose Neumann or Dirichlet conditions, depending on the problem in
hands. In my case, I have found simpler to measure experimentally n_max and
n_min of the stratification by using a refractometer and using these values
as input for the integration.

Best


Il giorno lun 22 lug 2019 alle ore 15:03 chandlersgk123 <
notifications@github.com> ha scritto:

**Comment by chandlersgk123** [comment]
thank you for your reply.
if i'm going to use this method to test the denstiy of ,say the hot flow from one hair drier.there's no glass and multi-layer
solution only hot gas flow, air ,then how to define n_max and n_min? .if n_max=n_min, the result would me zero?




------------------ 原始邮件 ------------------
发件人: "lillyverso"<notifications@github.com>;
发送时间: 2019年7月23日(星期二) 晚上11:52
收件人: "OpenPIV/bos"<bos@noreply.github.com>;
抄送: "方方の土の"<329928594@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [OpenPIV/bos] 2D poisson issue (#1)



Hello,
 
 the Poisson integration need two boundaries conditions to be solved. You
 might impose Neumann or Dirichlet conditions, depending on the problem in
 hands. In my case, I have found simpler to measure experimentally n_max and
 n_min of the stratification by using a refractometer and using these values
 as input for the integration.
 
 Best
 
 
 Il giorno lun 22 lug 2019 alle ore 15:03 chandlersgk123 <
 notifications@github.com> ha scritto:

**Comment by lillyverso** [comment]
Hello,

You may be able to find some relation that link n as function of
temperature for air flows. So, you have one boundary condition nmax at the
jet source. Then identify  the boundaries of the jet with some kind of
threshold on the piv velocity vectors and set nmin = nair at the room
temperature and then run the integration.

Best
Lilly

**Comment by chandlersgk123** [comment]
wow,intresting,thank you 




------------------ 原始邮件 ------------------
发件人: "lillyverso"<notifications@github.com>;
发送时间: 2019年7月24日(星期三) 晚上7:49
收件人: "OpenPIV/bos"<bos@noreply.github.com>;
抄送: "方方の土の"<329928594@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [OpenPIV/bos] 2D poisson issue (#1)



Hello,
 
 You may be able to find some relation that link n as function of
 temperature for air flows. So, you have one boundary condition nmax at the
 jet source. Then identify  the boundaries of the jet with some kind of
 threshold on the piv velocity vectors and set nmin = nair at the room
 temperature and then run the integration.
 
 Best
 Lilly
